services:
  - type: web
    name: travelmate-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MYSQL_HOST
        value: your-mysql-host
      - key: MYSQL_USER
        value: your-mysql-username
      - key: MYSQL_PASSWORD
        value: your-mysql-password
      - key: MYSQL_DB
        value: your-database-name
      - key: JWT_SECRET_KEY
        value: your-secret-key
