services:
  - type: web
    name: travelmate-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MYSQL_HOST
        value: mysql-1234.railway.internal
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: Abcd1234
      - key: MYSQL_DB
        value: travelmate
      - key: JWT_SECRET_KEY
        value: 3306
